spring:
  datasource:
    driver-class-name: org.h2.Driver
    url : jdbc:h2:mem:testdb
    useranme: sa
    password: '{cipher}b4a51ea0f4153dd4b11cbe55d05433286a68b4838a8e1b116910a0a6f62734d1'


token:
  expiration_time : 86400000
  secret: djoh1234!@_test

